### PR TITLE
Add carbon components react, sass, themes and update gatsby dependancies

### LINKED ISSUE #3: Import Carbon components
Carbon React components and styles must be imported to be used in creating a Gatsby site. Suggest copying from https://github.com/ibm-frontend/gatsby-starter-carbon--deprecated/issues/6

This issue is complete when:

- [ ]  carbon-components-react is a dependency in this repo
- [ ]    Carbon's stylesheet are imported into the demo page
- [ ]    Importing Carbon React components is straight forward without having to dive deep into node_modules for import paths (Import path resolving)

### LINKED ISSUE #9: Create Carbon theme
Using the Carbon theme creation GUI, create theme color variations to show that Carbon can be themed.

This issue is complete when:

- [ ] Add 1 or 2 color theming variables

When we create a new FED@IBM site, we can create a new theme

### PR DESCRIPTION
**Pull request by vpicone**
resolves #3 
resolves #9 

## What is this

This update includes the unopinionated default plugins provided by the default gatsby starter as well as the following features.

1. Carbon Components React
1. The new @carbon/themes package from Carbon Design@next
1. Sass integrations to allow for theming

## Motivation
* The design choices of the Fed@IBM site more closely align with the gatsby-site starter as opposed to the blogging starter.
* The best starters make no assumptions about the styling or purpose of the app.

This kit uses the core gatsby plugins with the minimum tooling required to use themed Carbon. That way, it requires minimal modifications to fit the user's design goals or styling preferences.

### Documentation
* How to for more objective tooling (styled-components, MDX)
* Elaborate on how Carbon Design can be incorporated and featured using this tooling
* Integrating @carbon/themes and other @carbon/elements to fill in the blanks around carbon-components-react

### Features
* Make the default Layout component more in-line with the Carbon recommendations
* Add Plex and typographic scale
* Add sizing units and scale 

https://gatsby-carbon-starter.now.sh/

### CODE REVIEW

**Comment by vpicone** [comment]
I hardly ever use sass so someone might want to check if I made any faux-pas in the _themes.scss

I assigned the green pallet to css-variables so we could use them in the APP without using sass outside of the layout component

**Review by alisonjoseph — COMMENTED** [review]
Overall this seems fine, however, it is a very bare bones install, which may be the goal? I’m not sure how opinionated you want this starter to be. 

Are you looking for current Carbon styles or the new v10 “duo/IDL2” styles? I see you’re pulling in v9 Carbon while also trying to use @carbon/themes

All of the @carbon/elements packages are designed to be used with the updated styles, currently you are pulling in the themes and v9 Carbon.

V10 Carbon is currently an alpha release `10.0.0-alpha.0` or you can use v9 Carbon and set the feature flag to turn on the v10 styles. 

You can see how I'm pulling in the Carbon styles w/ feature flags and elements packages here https://github.com/IBM-Design/design-website/blob/master/src/styles/index.scss

**Comment by vpicone** [comment]
@alisonjoseph Thanks for taking a look! I think keeping default tools to a core, essential, set makes the onboarding experience and maintenance of the project much more simple. Users could add the mdx plugin in a few lines if they wanted to use the starter as a blog. I definitely think docs that show how to incorporate more opinionated dependancies with carbon components would be a great addition.

Also, thanks for the theming info! I was just trying to use a new color swatch with the carbon-components-react library. I'm definitely open to other solutions than the naive one I ended up with.

**Comment by kellychurchill** [comment]
We definitely want to incorporate v10

Bare bones install could be fine but we should establish the criteria for what we would want to include in a Gatsby Carbon starter that we want to submit to Gatsby starter projects.

**Comment by vpicone** [comment]
From my experience, gatsby starters either fall into a standard app/site build or a blog build. The site build seemed most in line with the fed@ibm design goals. 

But I agree, I think guides demonstrating addition of more opinionated dependencies combined with carbon would be the way to go.

**Comment by kellychurchill** [comment]
Alison and I chatted a little bit after FEDucation. 

Since the goal of the Gatsby Carbon starter is to get a starter ready to submit to Gatsby, let’s keep as much of the mdx packages and and features in. Alison and I had selected that starter because we felt it was a good starter and the work to be done would be to make it into a Carbon starter. What you did here would be a good start for the FED website however so I don’t want to lose that. 

I think what would be a good idea is to create a new repo with the version in your PR.

**Comment by vpicone** [comment]
Gonna close this since I think we're looking for a more opinionated starter.

**Pull request closed without merging**
